### ISSUE TITLE
WHERE IS FALSE PARADISE SOURCE CODE

### ISSUE THREAD

**Issue by TheoDevelops** [4mbr0s3-2/FNF-Groovin-Docs#3]
4mbr0s3 please release the false paradise modchart client class, please 😭😭😭😭 🙏

**Comment by SanicBTW** [comment]
nuh uh

**Comment by 4mbr0s3-2** [comment]
# ok
[False Paradise FNF Source.zip](https://github.com/4mbr0s3-2/FNF-Groovin-Docs/files/14985960/False.Paradise.FNF.Source.zip)

**Comment by SanicBTW** [comment]
amazing

**Comment by Sword352** [comment]
so real

**Comment by TheoDevelops** [comment]
> # ok
> [False Paradise FNF Source.zip](https://github.com/4mbr0s3-2/FNF-Groovin-Docs/files/14985960/False.Paradise.FNF.Source.zip)
> 

NO WAY 😭😭
THANKSS

**Comment by AxorTheAxolotl** [comment]
### "**WHERE IS FALSE PARADISE SOURCE CODE**"

it can't be that easy.

it's that easy.
